version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.8.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.8.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:4.8.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub

  test-runner:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - selenium-hub
      - chrome
      - firefox
