name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Build and start Selenium Grid
      run: docker-compose up -d --build

    - name: Wait for Selenium Hub to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:4444/wd/hub/status | grep -q "ready"; then
            echo "Selenium Hub is ready"
            break
          fi
          echo "Waiting for Selenium Hub..."
          sleep 5
        done

    - name: Run tests
      run: docker-compose run test-runner

    - name: Stop Docker Compose
      run: docker-compose down
